baseURL = 'https://theashok.xyz'
languageCode = 'en-us'
title = 'XYZ About The Ashok'

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
title = 'Ashok Gelal'
author = "Ashok Gelal"
description = "I'm so sorry if I mispronounced my name"
profilePicture = "images/profile.png"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
